-- @PKGNAME@.MuddyHelper.lua — generated by `muddy unpack`.
--
-- Drop this into Mudlet, *below* the Muddy package in the Scripts tree, and it
-- hot-reloads @PKGNAME@ every time you rebuild it with `muddy`. `path` is the
-- project root (the folder you run `muddy` from); it points at where this
-- package was unpacked — change it if you move the project.

local name = @NAME@
local path = @PATH@

@PKGID@Helper = @PKGID@Helper or {watcher = nil}

-- Drop stale require()'d modules on uninstall so a reinstall runs fresh code
-- instead of cached copies left behind in package.loaded.
function @PKGID@Helper:killCache(pkg)
  for mod in pairs(package.loaded) do
    if mod:find(pkg) then
      package.loaded[mod] = nil
      debugc(f "Uncached {mod}")
    end
  end
end

function @PKGID@Helper:setup()
  ---@diagnostic disable-next-line: undefined-global
  if not Muddy then return end -- the Muddy package isn't installed yet
  if self.watcher then return end

  ---@diagnostic disable-next-line: undefined-global
  self.watcher = Muddy:new({
    path = path,
    watch = true,
    postremove = function() @PKGID@Helper:killCache(name) end,
  })

  debugc(f "Watching " .. name)
end

@PKGID@Helper:setup()
